# Generated by Django 5.2.5 on 2025-08-09 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='作品名')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('title_pending', models.CharField(blank=True, max_length=200, null=True, verbose_name='待审核作品名')),
                ('description_pending', models.TextField(blank=True, null=True, verbose_name='待审核简介')),
                ('ai_check_title', models.CharField(choices=[('pending', '待审核'), ('approved', '审核通过'), ('rejected', '审核不通过')], default='pending', max_length=20, verbose_name='标题AI审核状态')),
                ('ai_check_description', models.CharField(choices=[('pending', '待审核'), ('approved', '审核通过'), ('rejected', '审核不通过')], default='pending', max_length=20, verbose_name='简介AI审核状态')),
                ('adm_check_title', models.CharField(blank=True, choices=[('pending', '待审核'), ('approved', '审核通过'), ('rejected', '审核不通过')], max_length=20, null=True, verbose_name='标题管理员审核状态')),
                ('adm_check_description', models.CharField(blank=True, choices=[('pending', '待审核'), ('approved', '审核通过'), ('rejected', '审核不通过')], max_length=20, null=True, verbose_name='简介管理员审核状态')),
                ('title_reject_reason', models.TextField(blank=True, verbose_name='标题拒绝原因')),
                ('description_reject_reason', models.TextField(blank=True, verbose_name='简介拒绝原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_chapter_update', models.DateTimeField(blank=True, null=True, verbose_name='最后章节更新时间')),
                ('mongodb_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='MongoDB文档ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '作品',
                'verbose_name_plural': '作品',
                'db_table': 'books',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BookDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='草稿标题')),
                ('description', models.TextField(blank=True, verbose_name='草稿简介')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='books.book')),
            ],
            options={
                'verbose_name': '作品草稿',
                'verbose_name_plural': '作品草稿',
                'db_table': 'book_drafts',
            },
        ),
    ]
