# Generated by Django 4.2.23 on 2025-08-16 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='mongodb_id',
        ),
        migrations.CreateModel(
            name='ChapterDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField(verbose_name='章节序号')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='草稿标题')),
                ('content', models.TextField(blank=True, verbose_name='草稿内容')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_drafts', to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_drafts', to='books.book')),
            ],
            options={
                'verbose_name': '章节草稿',
                'verbose_name_plural': '章节草稿',
                'db_table': 'chapter_drafts',
                'unique_together': {('book', 'chapter_number')},
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField(verbose_name='章节序号')),
                ('title', models.CharField(max_length=200, verbose_name='章节标题')),
                ('content', models.TextField(verbose_name='章节内容')),
                ('title_pending', models.CharField(blank=True, max_length=200, null=True, verbose_name='待审核标题')),
                ('content_pending', models.TextField(blank=True, null=True, verbose_name='待审核内容')),
                ('ai_check_title', models.CharField(choices=[('pending', '待审核'), ('approved', '审核通过'), ('rejected', '审核不通过')], default='pending', max_length=20, verbose_name='标题AI审核状态')),
                ('ai_check_content', models.CharField(choices=[('pending', '待审核'), ('approved', '审核通过'), ('rejected', '审核不通过')], default='pending', max_length=20, verbose_name='内容AI审核状态')),
                ('adm_check_title', models.CharField(blank=True, choices=[('pending', '待审核'), ('approved', '审核通过'), ('rejected', '审核不通过')], max_length=20, null=True, verbose_name='标题管理员审核状态')),
                ('adm_check_content', models.CharField(blank=True, choices=[('pending', '待审核'), ('approved', '审核通过'), ('rejected', '审核不通过')], max_length=20, null=True, verbose_name='内容管理员审核状态')),
                ('title_reject_reason', models.TextField(blank=True, verbose_name='标题拒绝原因')),
                ('content_reject_reason', models.TextField(blank=True, verbose_name='内容拒绝原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='books.book', verbose_name='所属作品')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
                'db_table': 'chapters',
                'ordering': ['book', 'chapter_number'],
                'unique_together': {('book', 'chapter_number')},
            },
        ),
    ]
