# Generated by Django 4.2.23 on 2025-08-16 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_remove_book_mongodb_id_chapterdraft_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('content_pending', models.TextField(blank=True, null=True, verbose_name='待审核内容')),
                ('ai_check', models.CharField(choices=[('pending', '待审核'), ('approved', '审核通过'), ('rejected', '审核不通过')], default='pending', max_length=20, verbose_name='AI审核状态')),
                ('adm_check', models.CharField(blank=True, choices=[('pending', '待审核'), ('approved', '审核通过'), ('rejected', '审核不通过')], max_length=20, null=True, verbose_name='管理员审核状态')),
                ('reject_reason', models.TextField(blank=True, verbose_name='拒绝原因')),
                ('is_visible', models.BooleanField(default=False, verbose_name='是否可见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='books.book', verbose_name='所属作品')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='books.chapter', verbose_name='所属章节')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
