# Generated by Django 5.2.5 on 2025-08-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='显示名称'),
        ),
    ]
